spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: demo

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/testdb
    username: root
    password: 1234

#    url: jdbc:mariadb://mariadb-container:13333/testdb
#    url: jdbc:mysql://localhost:13333/testdb
#    username: root
#    password: 1234
#    hikari: # DB Pool Size
#      minimum-idle: 2
#      maximum-pool-size: 5
#  jpa:
#    hibernate:
#      #ddl option: none || validate || update | create | create-drop
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
  jpa:
    generate-ddl: true
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true