spring:
  application:
    name: swimpool_app
  datasource: # mysql 접속
#    url: jdbc:mysql://localhost:3306/swimpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# 접속 URL
#    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 드라이버 (MySQL 용도)
    url: jdbc:log4jdbc:mysql://localhost:3306/swimpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# 접속 URL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: swimmer  # mysql 유저
    password: test1234!  # mysql 유저 암호
  mustache:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      cache: false
  session:
    timeout: 120s
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.mjc813.swimpool_app
  configuration:
    map-underscore-to-camel-case: true
